# Generated by Django 4.2 on 2024-08-23 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0004_list_followers_count_list_likes_listfollowers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListFollowers',
            new_name='ListFollower',
        ),
    ]
