# Generated by Django 4.2 on 2024-09-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_remove_list_likes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listfollower',
            constraint=models.UniqueConstraint(fields=('user', 'list'), name='unique_user_list_follow'),
        ),
    ]
